import { App, Category } from '@/types/app';

export const FEATURED_APPS: App[] = [
  {
    id: 'feat-1',
    name: 'Nova Strike',
    developer: 'T Studios',
    category: 'Action',
    rating: 4.7,
    reviews: 128450,
    downloads: '10M+',
    size: '1.2 GB',
    price: 0,
    icon: 'NS',
    iconBg: '#1a1a2e',
    description: 'Experience the ultimate sci-fi action game. Battle across galaxies in stunning 3D environments. Upgrade your ship, unlock powerful weapons, and conquer the universe.',
    screenshots: [],
    tags: ['Action', 'Shooter', 'Multiplayer'],
    featured: true,
    featuredBanner: '/src/assets/banner1.jpg',
    featuredTitle: 'Nova Strike — Season 4 Begins',
    isInstalled: false,
    version: '4.2.1',
    lastUpdated: 'Apr 5, 2026',
    contentRating: '16+',
    type: 'game',
  },
  {
    id: 'feat-2',
    name: 'WorkFlow Pro',
    developer: 'Produx Labs',
    category: 'Productivity',
    rating: 4.5,
    reviews: 85230,
    downloads: '5M+',
    size: '45 MB',
    price: 0,
    icon: 'WP',
    iconBg: '#0052cc',
    description: 'Boost your productivity with the ultimate task and project management app. AI-powered scheduling, team collaboration, and real-time syncing across all your devices.',
    screenshots: [],
    tags: ['Productivity', 'Business', 'Tasks'],
    featured: true,
    featuredBanner: '/src/assets/banner2.jpg',
    featuredTitle: 'WorkFlow Pro — AI-Powered Productivity',
    isInstalled: false,
    version: '3.1.0',
    lastUpdated: 'Apr 1, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
  {
    id: 'feat-3',
    name: 'BeatWave Music',
    developer: 'SoundCore Inc.',
    category: 'Music & Audio',
    rating: 4.6,
    reviews: 212000,
    downloads: '50M+',
    size: '38 MB',
    price: 0,
    icon: 'BW',
    iconBg: '#6b21a8',
    description: 'Stream 90 million songs with no ads on the free tier. Discover new music with our AI DJ, download for offline listening, and share playlists with friends.',
    screenshots: [],
    tags: ['Music', 'Streaming', 'Audio'],
    featured: true,
    featuredBanner: '/src/assets/banner3.jpg',
    featuredTitle: 'BeatWave — 90M Songs, Zero Limits',
    isInstalled: true,
    version: '8.6.2',
    lastUpdated: 'Mar 28, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
];

export const SUGGESTED_APPS: App[] = [
  {
    id: 'sug-1',
    name: 'Bolt',
    developer: 'Bolt Technology',
    category: 'Travel',
    rating: 4.8,
    reviews: 542000,
    downloads: '100M+',
    size: '32 MB',
    price: 0,
    icon: 'B',
    iconBg: '#34d399',
    description: 'Get a ride in minutes. Bolt offers affordable rides, food delivery and more in one app.',
    screenshots: [],
    tags: ['Travel', 'Rides', 'Delivery'],
    isInstalled: false,
    version: '4.5.1',
    lastUpdated: 'Apr 3, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
  {
    id: 'sug-2',
    name: 'TikTok',
    developer: 'TikTok Pte. Ltd.',
    category: 'Entertainment',
    rating: 4.3,
    reviews: 18500000,
    downloads: '1B+',
    size: '118 MB',
    price: 0,
    icon: 'TT',
    iconBg: '#000000',
    description: 'Join your friends and discover videos you love on TikTok.',
    screenshots: [],
    tags: ['Social', 'Video', 'Entertainment'],
    isInstalled: false,
    version: '35.1.4',
    lastUpdated: 'Apr 7, 2026',
    contentRating: '13+',
    type: 'app',
  },
  {
    id: 'sug-3',
    name: 'Instaframe',
    developer: 'Meta Platforms',
    category: 'Social',
    rating: 4.6,
    reviews: 89000000,
    downloads: '1B+',
    size: '75 MB',
    price: 0,
    icon: 'IN',
    iconBg: '#e1306c',
    description: 'Share photos, videos and stories with friends and the world.',
    screenshots: [],
    tags: ['Social', 'Photos', 'Stories'],
    isInstalled: true,
    version: '315.0.0',
    lastUpdated: 'Apr 6, 2026',
    contentRating: '13+',
    type: 'app',
  },
  {
    id: 'sug-4',
    name: 'LinkedIn',
    developer: 'LinkedIn Corporation',
    category: 'Business',
    rating: 4.2,
    reviews: 3200000,
    downloads: '500M+',
    size: '56 MB',
    price: 0,
    icon: 'LN',
    iconBg: '#0077b5',
    description: 'Connect with professionals, find jobs, and grow your career.',
    screenshots: [],
    tags: ['Business', 'Networking', 'Jobs'],
    isInstalled: false,
    version: '9.1.112',
    lastUpdated: 'Apr 4, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
  {
    id: 'sug-5',
    name: 'FxPro',
    developer: 'FxPro Group',
    category: 'Finance',
    rating: 4.5,
    reviews: 142000,
    downloads: '10M+',
    size: '28 MB',
    price: 0,
    icon: 'FX',
    iconBg: '#111827',
    description: 'Trade Forex, Stocks, CFDs and more with advanced charting tools.',
    screenshots: [],
    tags: ['Finance', 'Trading', 'Investment'],
    isInstalled: false,
    version: '3.2.8',
    lastUpdated: 'Mar 30, 2026',
    contentRating: '18+',
    type: 'app',
  },
  {
    id: 'sug-6',
    name: 'Filmora',
    developer: 'Wondershare',
    category: 'Video',
    rating: 4.7,
    reviews: 945000,
    downloads: '50M+',
    size: '198 MB',
    price: 0,
    icon: 'FM',
    iconBg: '#1e3a5f',
    description: 'AI-powered video editor. Create stunning videos with templates, effects and music.',
    screenshots: [],
    tags: ['Video', 'Editor', 'Creative'],
    isInstalled: false,
    version: '13.4.00',
    lastUpdated: 'Apr 2, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
];

export const RECOMMENDED_APPS: App[] = [
  {
    id: 'rec-1',
    name: 'PDF Scanner Pro',
    developer: 'DocScan Studio',
    category: 'Productivity',
    rating: 4.6,
    reviews: 328000,
    downloads: '50M+',
    size: '24 MB',
    price: 0,
    icon: 'PS',
    iconBg: '#16a34a',
    description: 'Scan documents, receipts, and books with your camera. Auto-enhance and export as PDF.',
    screenshots: [],
    tags: ['Productivity', 'Scanner', 'PDF'],
    isInstalled: false,
    version: '2026.1.1',
    lastUpdated: 'Apr 1, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
  {
    id: 'rec-2',
    name: 'VivaVideo',
    developer: 'QuVideo Inc.',
    category: 'Video',
    rating: 4.4,
    reviews: 1250000,
    downloads: '100M+',
    size: '92 MB',
    price: 0,
    icon: 'VV',
    iconBg: '#ea580c',
    description: 'Edit videos like a pro. Hundreds of templates, effects, transitions and music.',
    screenshots: [],
    tags: ['Video', 'Editor', 'Templates'],
    isInstalled: false,
    version: '9.7.6',
    lastUpdated: 'Mar 25, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
  {
    id: 'rec-3',
    name: 'AI Chat Assistant',
    developer: 'T Intelligence',
    category: 'Productivity',
    rating: 4.8,
    reviews: 415000,
    downloads: '20M+',
    size: '31 MB',
    price: 0,
    icon: 'AI',
    iconBg: '#7c3aed',
    description: 'Your personal AI assistant. Ask anything, generate content, code, images and more.',
    screenshots: [],
    tags: ['AI', 'Assistant', 'Productivity'],
    isInstalled: false,
    version: '2.3.0',
    lastUpdated: 'Apr 7, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
  {
    id: 'rec-4',
    name: 'Candy Blast',
    developer: 'T Games Studio',
    category: 'Casual',
    rating: 4.5,
    reviews: 2100000,
    downloads: '500M+',
    size: '86 MB',
    price: 0,
    icon: 'CB',
    iconBg: '#db2777',
    description: 'Match candies, crush obstacles and unlock sweet rewards in this addictive puzzle game.',
    screenshots: [],
    tags: ['Casual', 'Puzzle', 'Match-3'],
    isInstalled: true,
    version: '1.264.1',
    lastUpdated: 'Apr 5, 2026',
    contentRating: 'Everyone',
    type: 'game',
  },
  {
    id: 'rec-5',
    name: 'SpeedRacer X',
    developer: 'Velocity Games',
    category: 'Racing',
    rating: 4.3,
    reviews: 580000,
    downloads: '20M+',
    size: '1.4 GB',
    price: 0,
    icon: 'SR',
    iconBg: '#dc2626',
    description: 'High-speed racing across 50+ tracks. Customize your car, race online, climb the leaderboards.',
    screenshots: [],
    tags: ['Racing', 'Multiplayer', 'Cars'],
    isInstalled: false,
    version: '3.0.1',
    lastUpdated: 'Mar 20, 2026',
    contentRating: 'Everyone',
    type: 'game',
  },
  {
    id: 'rec-6',
    name: 'MyFitness',
    developer: 'HealthTech Co.',
    category: 'Health',
    rating: 4.7,
    reviews: 892000,
    downloads: '50M+',
    size: '52 MB',
    price: 0,
    icon: 'MF',
    iconBg: '#0891b2',
    description: 'Track workouts, nutrition, sleep and more. Your complete health and fitness companion.',
    screenshots: [],
    tags: ['Health', 'Fitness', 'Tracker'],
    isInstalled: false,
    version: '5.8.3',
    lastUpdated: 'Apr 3, 2026',
    contentRating: 'Everyone',
    type: 'app',
  },
];

export const TOP_CHARTS_FREE: App[] = [
  { ...SUGGESTED_APPS[1], id: 'tc-1' },
  { ...RECOMMENDED_APPS[2], id: 'tc-2' },
  { ...FEATURED_APPS[2], id: 'tc-3' },
  { ...SUGGESTED_APPS[0], id: 'tc-4' },
  { ...RECOMMENDED_APPS[0], id: 'tc-5' },
  { ...SUGGESTED_APPS[2], id: 'tc-6' },
  { ...RECOMMENDED_APPS[5], id: 'tc-7' },
  { ...RECOMMENDED_APPS[1], id: 'tc-8' },
  { ...SUGGESTED_APPS[4], id: 'tc-9' },
  { ...SUGGESTED_APPS[5], id: 'tc-10' },
];

export const TOP_CHARTS_GAMES: App[] = [
  { ...FEATURED_APPS[0], id: 'tg-1' },
  { ...RECOMMENDED_APPS[3], id: 'tg-2' },
  { ...RECOMMENDED_APPS[4], id: 'tg-3' },
  { id: 'tg-4', name: 'Shadow Arena', developer: 'DarkByte Games', category: 'RPG', rating: 4.6, reviews: 320000, downloads: '10M+', size: '2.1 GB', price: 0, icon: 'SA', iconBg: '#1e1e2e', description: 'Epic fantasy RPG with real-time combat, 200+ heroes, and massive open world.', screenshots: [], tags: ['RPG', 'Action', 'Fantasy'], isInstalled: false, version: '2.8.4', lastUpdated: 'Mar 31, 2026', contentRating: '16+', type: 'game' },
  { id: 'tg-5', name: 'Block City', developer: 'CraftWorld', category: 'Simulation', rating: 4.4, reviews: 1800000, downloads: '200M+', size: '680 MB', price: 0, icon: 'BC', iconBg: '#16a34a', description: 'Build your own world block by block. Explore infinite worlds and survive the night.', screenshots: [], tags: ['Simulation', 'Building', 'Survival'], isInstalled: false, version: '1.20.1', lastUpdated: 'Apr 4, 2026', contentRating: 'Everyone 10+', type: 'game' },
  { id: 'tg-6', name: 'Pixel Warriors', developer: 'RetroForge', category: 'Action', rating: 4.2, reviews: 215000, downloads: '5M+', size: '120 MB', price: 0, icon: 'PW', iconBg: '#854d0e', description: 'Retro-style pixel art brawler. Fight through dungeons with friends.', screenshots: [], tags: ['Action', 'Pixel', 'Brawler'], isInstalled: false, version: '1.5.2', lastUpdated: 'Mar 15, 2026', contentRating: 'Everyone 10+', type: 'game' },
];

export const GAME_CATEGORIES: Category[] = [
  { id: 'gc-1', name: 'Action', icon: '🚁', color: '#ef4444', type: 'game' },
  { id: 'gc-2', name: 'Simulation', icon: '🎮', color: '#22c55e', type: 'game' },
  { id: 'gc-3', name: 'Puzzle', icon: '🧩', color: '#3b82f6', type: 'game' },
  { id: 'gc-4', name: 'Adventure', icon: '🧭', color: '#f59e0b', type: 'game' },
  { id: 'gc-5', name: 'Racing', icon: '🏁', color: '#8b5cf6', type: 'game' },
  { id: 'gc-6', name: 'Role Playing', icon: '⚔️', color: '#06b6d4', type: 'game' },
  { id: 'gc-7', name: 'Strategy', icon: '♟️', color: '#10b981', type: 'game' },
  { id: 'gc-8', name: 'Sports', icon: '🎾', color: '#f43f5e', type: 'game' },
  { id: 'gc-9', name: 'Card', icon: '🃏', color: '#ec4899', type: 'game' },
  { id: 'gc-10', name: 'Board', icon: '🎲', color: '#14b8a6', type: 'game' },
];

export const APP_CATEGORIES: Category[] = [
  { id: 'ac-1', name: 'Social', icon: '💬', color: '#3b82f6', type: 'app' },
  { id: 'ac-2', name: 'Productivity', icon: '⚡', color: '#f59e0b', type: 'app' },
  { id: 'ac-3', name: 'Entertainment', icon: '🎬', color: '#ef4444', type: 'app' },
  { id: 'ac-4', name: 'Music & Audio', icon: '🎵', color: '#8b5cf6', type: 'app' },
  { id: 'ac-5', name: 'Finance', icon: '💰', color: '#22c55e', type: 'app' },
  { id: 'ac-6', name: 'Health & Fitness', icon: '❤️', color: '#f43f5e', type: 'app' },
  { id: 'ac-7', name: 'Travel', icon: '✈️', color: '#06b6d4', type: 'app' },
  { id: 'ac-8', name: 'Education', icon: '📚', color: '#f97316', type: 'app' },
  { id: 'ac-9', name: 'Photography', icon: '📸', color: '#ec4899', type: 'app' },
  { id: 'ac-10', name: 'News', icon: '📰', color: '#64748b', type: 'app' },
];

export const SEARCH_SUGGESTIONS = [
  'AI apps', 'Soccer apps', 'Video players', 'Animation apps',
  'Music player', 'Baseball apps', 'Photo editors', 'Fitness trackers',
  'Language learning', 'Meditation apps', 'Budget tracker', 'News reader',
];

export const ALL_APPS: App[] = [
  ...FEATURED_APPS,
  ...SUGGESTED_APPS,
  ...RECOMMENDED_APPS,
  ...TOP_CHARTS_GAMES.slice(3),
];
